// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9yu88Khia2gwFDx19FtvTyfKJgLy7aA',
    appId: '1:205076184054:web:6e5d5d501d17fee87925d7',
    messagingSenderId: '205076184054',
    projectId: 'psyflow-613bf',
    authDomain: 'psyflow-613bf.firebaseapp.com',
    storageBucket: 'psyflow-613bf.firebasestorage.app',
    measurementId: 'G-WDMV5YZH3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTFGhHAV5niFhzUH3d5W6lA4p3EVIe1c',
    appId: '1:205076184054:android:4507fad20576644b7925d7',
    messagingSenderId: '205076184054',
    projectId: 'psyflow-613bf',
    storageBucket: 'psyflow-613bf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIezuatELBiuWjkRdvTQmXtA9qMv-tdjA',
    appId: '1:205076184054:ios:5336107465f3d9a37925d7',
    messagingSenderId: '205076184054',
    projectId: 'psyflow-613bf',
    storageBucket: 'psyflow-613bf.firebasestorage.app',
    iosBundleId: 'com.example.psyflowApp',
  );
}
