// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiDYnfWzFvq0f10F-BKcVVM7vdSJtODuU',
    appId: '1:484328099680:web:192bec7212eee2f96f5805',
    messagingSenderId: '484328099680',
    projectId: 'psyflow-47d0e',
    authDomain: 'psyflow-47d0e.firebaseapp.com',
    storageBucket: 'psyflow-47d0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1C2j8qphfWxMDhu-Gk6EDg6-hA6itPww',
    appId: '1:484328099680:android:95c29ee3b587a2d06f5805',
    messagingSenderId: '484328099680',
    projectId: 'psyflow-47d0e',
    storageBucket: 'psyflow-47d0e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-5D2kFJuOiDIU4Z6YGhu2o4rG2hOkvM',
    appId: '1:484328099680:ios:e27b1c7d21b428806f5805',
    messagingSenderId: '484328099680',
    projectId: 'psyflow-47d0e',
    storageBucket: 'psyflow-47d0e.firebasestorage.app',
    iosBundleId: 'com.example.psyflowApp',
  );
}
